### ISSUE TITLE
Need a GUI for newbie users, that works on 3 major platform (Lin/Win/Mac)

### ISSUE THREAD

**Issue by stdevPavelmc** [skycoin/skyflash#1]
A GUI is needed for normal users, it must work in the three major platforms Linux/Window/MacOS with the following features:

- [x] Auto Download of the official skybian image 
  - [x] Or pick up a local copy
- [x] Network config (skyminners defaults or custom one) 
- [x] Image build processing
- [x] Image flash processing
- [x] As user-friendly as possible with tool-tips and a logic work flow

Will use python3 setuptools to handle the multi-OS installation (Linux/Windows/MacOS)

**Comment by olemis** [comment]
@stdevPavelmc I see no PR . Have you uploaded the changes ?

**Comment by stdevPavelmc** [comment]
This is a wip, this is the issue against I'm working on a [yet local] branch.
I raised it to get a kind of roadmap with steps to show progress and get feedback/tips/critics from the team.

**Comment by olemis** [comment]
@stdevPavelmc marked some as done , per your comments above

**Comment by stdevPavelmc** [comment]
That's a mistake, sorry, fixing that...

**Comment by stdevPavelmc** [comment]
Download of files is working in HTTP/HTTPS but Github files under "Releases" is not sending "Content-Length" header, so I'm working on a solution for that...

Main consequences: Progress will be undetermined and no ETA will be calculated.

**Comment by stdevPavelmc** [comment]
Image selection (either download or pick up a local copy) is working, the mentioned problem about not getting the progress bar is fixed.

Now working on Network config and validation.

**Comment by stdevPavelmc** [comment]
Download a Official Skybian release is working now.
Browse for a local copy of the Official Skybian release is working also.

The file must be the tarred and/or compressed  release file ( file ending with .tar / .tar.gz / .tar.xz / .tar.bz2)

Now start the step of network configuration and image building, we are 50% deep in the first full version.

**Comment by stdevPavelmc** [comment]
At this point the tools is capable of download + config + build a USABLE skybian OS image :tada: . Some validation and UI issues remains on the TODO list, but main functionality is there already.

**Comment by LateusBetelgeuse** [comment]
One of your requirements for the GUI for Windows is deliver it as a .exe file. In Linux that's is possible by using an AppImage, on MacOS you have the DMG image file. However, our awesome Windows don't have such capabilities. The most closer behavior is a static executable. But Qt uses dynamic linking by default, and if you want to use static linking you have to recompile the whole Qt library. It's no so difficult, I've done that many times with Widgets. However, with QML I've facing some serious problems on Windows, for example, graphic's shaders are off. I report that issue (see [QTBUG-72810](https://bugreports.qt.io/browse/QTBUG-72810)) and they said: _"I do think we should test static builds more than we do today and maybe provide packages"_
So, if you want a .exe, you should consider using an installer. You might want [Qt Installer Framework](http://download.qt.io/official_releases/qt-installer-framework/), or [NSIS](https://sourceforge.net/projects/nsis/), but it's a matter of tastes.

**Comment by stdevPavelmc** [comment]
This issue will be closed and split on the task related to completion of the main objective, main ones are: #20 Mac Support  and Windows flashing support (will be filled soon.)
