### ISSUE TITLE
Need CI/CD for Windows and MacOS

### ISSUE THREAD

**Issue by stdevPavelmc** [skycoin/skyflash#14]
Actually the CI/CD via travis is only for linux, need to be updated to work on windows (via docker + wine) and MacOS.

Also need the deploy section for all 3 OSs.

**Comment by gz-c** [comment]
appveyor can be used for Windows

**Comment by stdevPavelmc** [comment]
At this point travis can test & build the linux dist files:
- Linux 64bits standalone binary
- deb installation with dependencies

Work now will be focused on generating the .exe file for windows.

**Comment by stdevPavelmc** [comment]
Will concentrate now in CD/CI for windows to close this thread, as macOS will have his own issue

**Comment by stdevPavelmc** [comment]
CI/CD for windows and Linux is in place, tested on various variants of the mentioned OS.

MacOS Will be addressed in a particular issue later

**Comment by stdevPavelmc** [comment]
Closed by skycoin/skyflash https://github.com/skycoin/skyflash/pull/18
