### ISSUE TITLE
Repo description line is misleading Skyflash as a CLI tool

### ISSUE THREAD

**Issue by stdevPavelmc** [skycoin/skyflash#25]
## Expected Behavior
Description line must express the goal and main feature, something like this:

"Utility to download, configure & flash the Skybian OS to the Skyminers SD cards"

## Actual Behavior
Description line talks about a CLI tool only... and Skyflash is a GUI tool from a time ago...

## Possible Solution
Please update the description line, I don't have privileges to do it.

**Comment by olemis** [comment]
> Please update the description line, I don't have privileges to do it.

same here , has to be done by @gz-c
