### ISSUE TITLE
Rename minion-X to node-X

### ISSUE THREAD

**Issue by Asgaror** [skycoin/skyflash#26]
Naming convention of the previous Skywire guides & resources always referred to secondary nodes as 'nodes' and not 'minions'. 

I suggest to replace any occurence of `minion-X` with `node-X` whereby `X` refers to the respective number of the `node/minion`. The Skybian GUI shows 'minion-X' during the built procedure and in the image selection for step 4 'Flash the images'.

![image](https://user-images.githubusercontent.com/32180146/59048652-96e38880-8886-11e9-82bf-74e491dc513f.png)

**Additional context**
- [Skywire readme.md](https://github.com/skycoin/skywire/blob/master/README.md) -> refers to `nodes` 
- [Skywire installation guide](https://github.com/skycoin/skywire/wiki/Skyminer-Skywire-installation-guide) -> refers to `nodes`
- [Skywug user guides](https://skywug.net/forum/Forum-Skywire) -> refer to `nodes`

**Comment by Asgaror** [comment]
Same goes for the stored images on disk which are named `Skybian-minion-X.img` whereby `X` refers to the respective number of the `node/minion`.

**Comment by stdevPavelmc** [comment]
Makes sense and is easy to fix, working on it ASAP, thanks for the bug report.

**Comment by stdevPavelmc** [comment]
Closed by PR #36
