### ISSUE TITLE
Add information where the built images are stored

### ISSUE THREAD

**Issue by Asgaror** [skycoin/skyflash#28]
**Is your feature request related to a problem? Please describe.**
After building the images I had to guess that the built images were stored in the home directory (running Ubuntu).

**Describe the solution you'd like**
Add a popup or some sort of information that informs the user where the built images are being stored in case Step 4 of the Skyflash GUI doesn't work and they have to use balenaEtcher or similar flashing softwares.

**Describe alternatives you've considered**
Query the user using a qt file dialog to select the storage directory of the built images.

**Comment by stdevPavelmc** [comment]
It's a reasonable issue, even I like the alternative you proposed:

Suppose you are running on a system with a small SSD for the system and you have not enough free space for all the images, in the actual situation build (step 3) will fail.

Querying the users about the output folder is a must on this case, what would the better alternative in your opinion?

1. A pop-up upon first start (only on first start, may reside on the "File" menu under "Working directory") with a welcome message explaining we need a "working directory" with at least ~20 GB of free space to work and suggesting the default one with the option to select another.
2. A pop-up once you click on the "Build Images" button asking to use the default location (showing the path) or  pick another place for the images.
3. Any other idea...

Looking forward to fix this in the better way.

**Comment by Asgaror** [comment]
@stdevPavelmc 
I'd prefer the second option. This way the user is able to select different directories if he has to build different images which different IP settings in case he owns multiple miners.

**Comment by stdevPavelmc** [comment]
> @stdevPavelmc
> I'd prefer the second option. This way the user is able to select different directories if he has to build different images which different IP settings in case he owns multiple miners.

Roger, seems the most accurate solution and accomplish all goals we need: inform the user of the storage place and let him pick another location (even for a second set of images for a different miner)

Working on it.

**Comment by stdevPavelmc** [comment]
Closed via PR #46
