### ISSUE TITLE
Open user's manual 'Help' function defaults to develop

### ISSUE THREAD

**Issue by Asgaror** [skycoin/skyflash#30]
## Expected Behavior
Open the user manual of the respective branch that the program was started in.

## Actual Behavior
Defaults to the user manual on develop.

### Master:
  1. `git checkout master` 
  2. Start `skyflash-gui.py`
  3. Use menu bar `Help` to open the `User's manual`

### Develop:
  1. `git checkout develop` 
  2. Start `skyflash-gui.py`
  3. Use menu bar `Help` to open the `User's manual`

Both open https://github.com/skycoin/skyflash/blob/develop/USER_MANUAL.md 

## Specifications

  - Version: `None`, no release on current [develop branch](https://github.com/skycoin/skyflash/tree/develop)
  - Platform: 
```NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
```

**Comment by stdevPavelmc** [comment]
Closed by #37
