### ISSUE TITLE
Rephrase content in .about

### ISSUE THREAD

**Issue by Asgaror** [skycoin/skyflash#31]
**Is your feature request related to a problem? Please describe.**
.about page could be rephrased.
![image](https://user-images.githubusercontent.com/32180146/59097767-b3330400-891e-11e9-811d-0e221ad0b98c.png)

**Describe the solution you'd like**
[Skyflash](https://github.com/skycoin/skyflash) is the official tool to configure, build and flash the Skyminer images based on [Skybian](https://github.com/skycoin/skybian).

Current version: v0.0.3-rc

**Comment by stdevPavelmc** [comment]
Closed by PR #34
