### ISSUE TITLE
GUI displays no version of Skybian image

### ISSUE THREAD

**Issue by Asgaror** [skycoin/skyflash#32]
**Is your feature request related to a problem? Please describe.**
The skyflash gui doesn't display the version of the downloaded Skybian image or of the existing lokal image. 
![image](https://user-images.githubusercontent.com/32180146/59098380-66502d00-8920-11e9-8f6e-a6a4d2b29af0.png)
![image](https://user-images.githubusercontent.com/32180146/59098397-723bef00-8920-11e9-9837-13319380d770.png)

**Describe the solution you'd like**
Add version number of the Skybian image:
- that is being downloaded
- that is being extracted
- that was found on disk

In generall, all mentions of the image should include the version number

**Comment by stdevPavelmc** [comment]
Closed via PR #42
