### ISSUE TITLE
Linux .deb file is only for ubuntu bionic 18.04

### ISSUE THREAD

**Issue by stdevPavelmc** [skycoin/skyflash#40]
## Expected Behavior
Linux [name]_all.deb file must work on all deb based distros, because of the "_all" in the name, but no, it'ts in fact for the Ubuntu 18.04 LTS

## Actual Behavior
Users see the .deb file with the [name]**_all**.deb format and assume it will work on all deb based Linux distros, but no, it only works on Ubuntu Bionic 18.04
It will fail to install in other distros not based on that version of Ubuntu.

## Steps to Reproduce the Problem
Try to install the deb file in debian 9 or Ubuntu 16.04, it will fail because of the dependencies.

## Possible Solution
- Change the "_all" in the name of the pkg to "bionic" to sign that the .deb package is for bionic & compatibles only.
- Make a note on the readme & user's manual to clarify this.

**Comment by stagedatalosstest** [comment]
HelloWorld

**Comment by stdevPavelmc** [comment]
I'm thinking a few possible solution to this after some research:

1. Add the "-bionic.deb" ending to the file to warn users that it's only for ubuntu bionic
2. Pack the standalone version of skyflash in a deb file.
3. Not to release a .deb file

First case is just a warning, as you can install it over any deb based linux so it will not stop users to try it on other distros and problems will arose.

Second case is most universal but will generate a bulky deb file (~40MB) and is just another way of install the static version, so why bother with it?  

Third case is radical, but a definitive fix.

**Comment by stdevPavelmc** [comment]
After some debate and research I'm thinking on dropping the .deb releases of skyflash in favour of the .whl (python wheel) variant, that will ease the devs & user's life, dependencies will be more easy handled...

In that way you simply will do a "pip install skyflash" and that's all, pip will take care of the dependencies.

Pro? Cons?

**Comment by stdevPavelmc** [comment]
Closed via PR #44

**Comment by stdevPavelmc** [comment]
See https://github.com/simelo/skycoin-deb/issues/12 for more details, will pack the standalone app.
